In [1]:
import gymnasium as gym
import numpy as np

In [2]:
env = gym.make("FrozenLake-v1", render_mode="human")
observation, _ = env.reset()

print(f"Espaces d'actions : {env.action_space}")
print(f"Espaces d'observation: {env.observation_space}")

for _ in range(100):
    action = env.action_space.sample()
    observation, reward, done, _, _ = env.step(action)

    print(f"Action : {action}, Observation : {observation}, Reward : {reward}")

    if done:
        observation, _ = env.reset()

env.close()

Espaces d'actions : Discrete(4)
Espaces d'observation: Discrete(16)
Action : 1, Observation : 4, Reward : 0.0
Action : 0, Observation : 0, Reward : 0.0
Action : 1, Observation : 4, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action : 0, Observation : 0, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action : 0, Observation : 4, Reward : 0.0
Action : 2, Observation : 8, Reward : 0.0
Action : 0, Observation : 8, Reward : 0.0
Action : 0, Observation : 8, Reward : 0.0
Action : 0, Observation : 12, Reward : 0.0
Action : 2, Observation : 0, Reward : 0.0
Action : 0, Observation : 0, Reward : 0.0
Action : 1, Observation : 0, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action : 2, Observation : 0, Reward : 0.0
Action : 1, Observation : 4, Reward : 0.0
Action : 1, Observation : 5, Reward : 0.0
Action : 0, Observation : 0, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action : 2, Observation : 1, Reward : 0.0
Action : 1, Observation : 2, Reward : 0.0
Action 

In [4]:
env = gym.make("FrozenLake-v1", render_mode="human")
observation, _ = env.reset()

print(f"Espaces d'actions : {env.action_space}")
print(f"Espaces d'observation: {env.observation_space}")

for _ in range(100):
    action = env.action_space.sample()
    observation, reward, done, _, _ = env.step(action)

    print(f"Action : {action}, Observation : {observation}, Reward : {reward}")

    if done:
        observation, _ = env.reset()

env.close()

Q_table = np.zeros((16, 4))  # 16 états, 4 actions
print("Q-table initialization :")
print(Q_table)

Espaces d'actions : Discrete(4)
Espaces d'observation: Discrete(16)
Action : 1, Observation : 0, Reward : 0.0
Action : 2, Observation : 0, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action : 0, Observation : 4, Reward : 0.0
Action : 1, Observation : 5, Reward : 0.0
Action : 3, Observation : 1, Reward : 0.0
Action : 3, Observation : 1, Reward : 0.0
Action : 0, Observation : 0, Reward : 0.0
Action : 3, Observation : 1, Reward : 0.0
Action : 1, Observation : 5, Reward : 0.0
Action : 0, Observation : 0, Reward : 0.0
Action : 1, Observation : 1, Reward : 0.0
Action : 2, Observation : 1, Reward : 0.0
Action : 3, Observation : 2, Reward : 0.0
Action : 1, Observation : 1, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action : 2, Observation : 0, Reward : 0.0
Action : 1, Observation : 4, Reward : 0.0
Action : 1, Observation : 8, Reward : 0.0
Action : 1, Observation : 9, Reward : 0.0
Action : 2, Observation : 13, Reward : 0.0
Action : 2, Observation : 9, Reward : 0.0
Action 

In [ ]:
env = gym.make("FrozenLake-v1", render_mode="human")
observation, info = env.reset(seed=42) 

print(f"Espace d'actions : {env.action_space}")
print(f"Espace d'observations : {env.observation_space}")

n_states = env.observation_space.n
n_actions = env.action_space.n
Q_table = np.zeros((n_states, n_actions))

print("Q-table initiale :")
np.set_printoptions(formatter={'float': '{: .1f}'.format}, linewidth=75)
print(Q_table)

alpha = 0.1       
gamma = 0.99     
epsilon = 1.0    
epsilon_decay = 0.995
epsilon_min = 0.01
num_episodes = 5000

for episode in range(num_episodes):
    state, info = env.reset()
    terminated, truncated = False, False

    while not terminated and not truncated:
        
        if np.random.rand() < epsilon:
            action = env.action_space.sample()  
        else:
            action = np.argmax(Q_table[state, :]) 

        next_state, reward, terminated, truncated, info = env.step(action)

        Q_table[state, action] = Q_table[state, action] + alpha * (
            reward + gamma * np.max(Q_table[next_state, :]) - Q_table[state, action]
        )

        state = next_state

    epsilon = max(epsilon * epsilon_decay, epsilon_min)

    if (episode + 1) % 500 == 0:
        print(f"Épisode {episode + 1}, Epsilon: {epsilon:.4f}")

print("\nQ-table après entraînement :")
print(Q_table)

num_test_episodes = 100
success_count = 0

for episode in range(num_test_episodes):
    state, info = env.reset()
    terminated, truncated = False, False

    while not terminated and not truncated:
        action = np.argmax(Q_table[state, :])  
        next_state, reward, terminated, truncated, info = env.step(action)
        state = next_state

    if terminated and reward == 1.0:  
        success_count += 1

success_rate = (success_count / num_test_episodes) * 100
print(f"\nSuccès sur {num_test_episodes} épisodes : {success_count}")
print(f"Taux de réussite : {success_rate:.2f}%")

env.close()


Espace d'actions : Discrete(4)
Espace d'observations : Discrete(16)
Q-table initiale :
[[ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]
 [ 0.0  0.0  0.0  0.0]]
